version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-playground
    environment:
      MONGO_INITDB_ROOT_USERNAME: syneto
      MONGO_INITDB_ROOT_PASSWORD: '*secret00*'
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongodb_network
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-playground
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: syneto
      ME_CONFIG_MONGODB_ADMINPASSWORD: '*secret00*'
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
     - 8081:8081
    networks:
      - mongodb_network
    depends_on:
      - mongodb

networks:
  mongodb_network:

volumes:
  mongodb_data: